---
title: ""
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Erstellung des Versuchsplans:
```{r}
library(agricolae)
vormittags <- design.crd(c("in","out"),serie=0,c(5,5), seed = 2)$book
vormittags$zwei <- design.crd(c("in","out"),serie=0,c(5,5), seed = 4)$book[,3]
vormittags$drei <- design.crd(c("in","out"),serie=0,c(5,5), seed = 6)$book[,3]

nachmittags <- design.crd(c("in","out"),serie=0,c(5,5), seed = 8)$book
nachmittags$zwei <- design.crd(c("in","out"),serie=0,c(5,5), seed = 3)$book[,3]
nachmittags$drei <- design.crd(c("in","out"),serie=0,c(5,5), seed = 1)$book[,3]

versuchsplan <- list(vormittags=vormittags,nachmittags=nachmittags)
versuchsplan
```

### Bestimmung der Stichprobengröße:
```{r,warning=FALSE}
#Bestimmung der Stichprobengroesse fuer zweistichproben t Test:
alpha <- 0.05
f1 <- function(x){
  p1 <- pt(q=qt(df=2*(x-1),p=0.975),df=2*(x-1),ncp=sqrt(x/2))
  p2 <- pt(q=-qt(df=2*(x-1),p=0.975),df=2*(x-1),ncp=sqrt(x/2))
  p1-p2
}
plot(f1(1:70),ylab ="W'keit Fehler 2. Art",xlab="Stichprobenumfang n",main = "Zweiseitiger Zweistichproben t-Test",type = "l")  
abline(h=0.2,col="red")
abline(v=17,col="red")

```

