---
title: "Auswertung des Helikopterexperiments"
author: "Danuscha Große-Hering"
date: "05.Juli 2021"
output:
 # extra_dependencies: ["bbm", "threeparttable"]
  pdf_document: default
---
```{r}
#setwd("C:\\Users\\danus\\OneDrive\\Uni\\4.Semester\\Grundlagen der Versuchspalnung\\1.Experiment\\GdV-Experiment-1\\Experiment 3")
```

# Versuchsablauf

# Screening
```{r}

library(SixSigma)


ExperimentDesign  = expand.grid(A = c(-1, 1), B = c(-1,1), C = c(-1, 1), D = c(-1,1), E = c(-1,1) )
"F" = ExperimentDesign$A * ExperimentDesign$C * ExperimentDesign$D
G = ExperimentDesign$A * ExperimentDesign$B * ExperimentDesign$C



ExperimentDesign$F = F
ExperimentDesign$G = G

```

```{r}
Screening <- read.csv("Screening.CSV", sep = ";",dec = ",")
S <- Screening[order(Screening[,2]),]
S <-cbind(S, ExperimentDesign)
```

```{r}
summary(lm(Zeit.ohne.Klammer ~A+B+C+D+E+F+G, data= S))
```
```{r}
summary(lm(Zeit.mit.Klammer ~A+B+C+D+E+F+G, data= S))
#install.packages("BsMD")
library(BsMD)
par(mfrow = c(1,2))
DanielPlot(lm(Zeit.ohne.Klammer ~ A +B + C + D+E+F+G, data = S), pch = 15)
DanielPlot(lm(Zeit.mit.Klammer ~A + B + C + D+E+F+G, data= S), pch = 15)
```

# Optimierung
```{r}
Optimierung <-read.csv("Optimierung.CSV", sep = ";",dec = ",")

#erster Durchlauf
set.seed(1735)
p1 <-expand.grid(A = c(-1,0, 1),  G = c(-1,0,1) )
p1 <- cbind(1:9,p1)
#zweiter Durchlauf
set.seed(1736)
s <-sample(1:9,9)
p2 <-p1[s,]


p <- rbind(p1,p2)
names(p)[1] <- "Nr."
a <-round(sqrt(0.5*(sqrt(9*18)-9)), digits=3)
p[which(p$A*p$G ==0),2:3] <- p[which(p$A*p$G ==0),2:3] *a

o1 <-cbind(Optimierung,p[1:9,2:3])

o2 <- o1[,-3]
o3 <- o1[,-2]

names(o2)[2] <- "Zeit"
names(o3)[2] <- "Zeit"

o <- rbind(o2,o3)
o$Asquare <- o$A^2
o$Gsquare <- o$G^2

lm(Zeit ~A + Asquare+G+Gsquare, data = o)

##MIT Wechselwirkung
MM = lm(Zeit ~A * G  + Asquare+Gsquare, data = o)
thetaM <- MM$coefficients
modellM <- function(t){
  thetaM[1] + thetaM[2] * t[1] + thetaM[4] * t[1]^2 + thetaM[3] * t[2] + 
    thetaM[5] * t[2]^2 + thetaM[6] * t[1] * t[2]
}

MIT = optim(c(1,1),  function(x) -modellM(x), method = "L-BFGS-B", 
             lower = c(-1.365, -1.365), upper = c(1.365,1.365))

modellM(c(1.365, -1.365))
MIT

## OHNE

M = lm(Zeit ~A + G  + Asquare+Gsquare, data = o)
theta <- M$coefficients
modell <- function(t){
  theta[1] + theta[2] * t[1] + theta[4] * t[1]^2 + theta[3] * t[2] + 
    theta[5] * t[2]^2 #+ theta[6] * t[1] * t[2]
}

OHNE = optim(c(0.5,0.5),  function(x) -modell(x), method = "L-BFGS-B", 
      lower = c(-1.365, -1.365), upper = c(1.365,1.365))
OHNE
```


$\Rightarrow f(x_1,x_2)=3.47+00.44 \cdot x_1+0.06 \cdot x_1^2-0.67 \cdot x_2 + 0.29 \cdot x_2^2 \Rightarrow \frac{\partial{f}}{\partial{x}}= \begin{pmatrix}
0.44+0.12 \cdot x_1 \\
-0.67+0.58 \cdot x_2
\end{pmatrix}$


```{r}
y_observ=c(1.2,0.5,1.5,1.3,0.2,1.4)
data_set=data.frame(y=y_observ)
data_set$A = c(-1,0,1,-1,0,1)
data_set$Asquare = data_set$A^2
lm(y~A+Asquare, data=data_set)
```

